### ISSUE TITLE
Singleton.hpp missing and missing #include <new> for std::bad_alloc in MemAlloc.cpp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dtecta/motion-toolkit#1]
```
Compile and see the errors.

Attached is a patch that fixes both issues.
```

Original issue reported on code.google.com by `erwin.coumans` on 5 Mar 2015 at 4:25

Attachments:
- [patch.diff](https://storage.googleapis.com/google-code-attachments/motion-toolkit/issue-1/comment-0/patch.diff)

**Comment by dtecta** [comment]
Issues have been fixed in the latest code
