### ISSUE TITLE
Question: why the error for multiplication and division is x.error() + y.error() + T(1) ? 

### ISSUE THREAD

**Issue by blackball** [dtecta/motion-toolkit#2]
Hi, I am reading your GDC slides and the ErrorTracer implementation. I am a little bit confused about the error propagation on multiplication and division. 

```C++
    template <typename T>
    FORCEINLINE 
    ErrorTracer<T> operator*(const ErrorTracer<T>& x, const ErrorTracer<T>& y)
    {
        return ErrorTracer<T>(x.value() * y.value(), 
                              x.error() + y.error() + T(1));
    }
    
    template <typename T>
    FORCEINLINE
    ErrorTracer<T> operator/(const ErrorTracer<T>& x, const ErrorTracer<T>& y) 
    {
        return ErrorTracer<T>(x.value() / y.value(), 
                              x.error() + y.error() + T(1));
    }

```

In above codes, why the new error is 
```C++
x.error() + y.error() + T(1)
```
?

Thanks!

**Comment by blackball** [comment]
Also ErrorTracer will give bigger errors when there're more operations, which is not always correct. For example, the kahan summation has way bigger errors than the naive summation, which is not true.    

```C++
Scalar a,b,c;
a = b - c; 
a = b + c - c -c; // error is bigger
```

**Comment by dtecta** [comment]
First of all, the error returned by ErrorTracer is, as its name suggests, an upper bound for the actual relative error. This means that the maximum relative error r_a of a  computed value a' with respect to its theoretical value is given by a' = a * (1 + r_a)  where -a.maxRelativeError() <= r_a <= a.maxRelativeError().  Now, Let x' and y' be two computed values with relative error r_x and r_y. Then the relative error of x' * y' would be x' * y' * (1 + epsilon) = x * (1 + r_x)  * y * (1 + r_y) * (1 + epsilon) = x * y * (1 + r_x + r_y + epsilon + r_x * r_y + r_x * epsilon + r_y * epsilon + r_x * r_y * epsilon). Under the assumption that relative errors are small in comparison to 1 we may drop all second and higher-order terms. We then get

x' * y' = x * y * (1 + r_x + r_y + epsilon),

so the relative error rx + ry + epsilon. Note that for the mError field the unit is taken to be epsilon. (maxRelativeError() returns mError * gMachineEpsilon.) For operator/ follows a similar deduction.

The fact that for b + c - c - c the error is bigger than for b - c is fully justified. For instance, take b = 1e6 + 1e-1, c = 1e6. Then, the lower bits of b's significant are flushed by adding and subtracting c. This is the whole point of running ErrorTracer. ErrorTracer accounts for the flushed bits of the significant, so adding and subtracting numbers (even if they are the same) shows in the relative error.

**Comment by blackball** [comment]
Thanks for your reply. 

So from my understanding now, ErrorTracer is only giving an upper bound of the relative errors(this bounds could be overestimated), but the relative errors here don't necessarily proof the codes are more stable/accurate or not. 

Since I don't have doubts at the codes now, I will close the issue.
